defmodule FishScrapperTest do
  use ExUnit.Case
  doctest FishScrapper

  @body """
  \r\n\r\n<!DOCTYPE html>\r\n<html lang=\"en\">\r\n\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head id=\"ctl00_Head1\"><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" /><meta charset=\"UTF-8\" /><title>\r\n\tVermont Department of Fish & Wildlife\r\n</title>\r\n<link href=\"Content/bootstrap.min.css\" rel=\"stylesheet\" /><link href=\"Styles/styles.css\"
   rel=\"stylesheet\" /> <!-- There is a gridview style class within styles at the bottom that we commented out MG/JK -->\r\n    <link href=\"Styles/override.css\" rel=\"stylesheet\" /><link href=\"Styles/normalize.css\" rel=\"stylesheet\" /> \r\n\r\n    <script src=\"//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js\"></script>\r\n    <link rel=\"icon\" type=\"image/png\
  " href=\"Images/favicon.png\" /><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n    <!--[if lte IE 8]>\r\n    <script src=\"http://html5shiv.googlecode.com/svn/trunk/html5.js\"></script>\r\n    <![endif]-->\r\n</head>\r\n\r\n    <style type=\"text/css\">\r\n \t\r\n        .links2 {\r\n\t        font-family: Verdana, Arial, Helvetica, sans-serif;\r\n\
  t        font-size: 11px;\r\n\t        font-weight: normal;\r\n\t        color: #006633; \r\n         }\r\n\r\n\r\n        .linksL {\r\n\t        font-family: Verdana, Arial, Helvetica, sans-serif;\r\n\t        font-size: 14px;\r\n\t        font-weight: normal;\r\n\t        color: #006633;\r\n\t        text-decoration : underline;\r\n        }\r\n        .bullets2 {\r\n\t
  font-family: Verdana, Arial, Helvetica, sans-serif;\r\n\t        font-size: 10px;\r\n\t        font-weight: bold;\r\n\t        color: #006633;\r\n\t        text-decoration: none;\r\n        }\r\n\r\n        .alerttext{\r\n\t        font-family: Verdana, Arial, Helvetica, sans-serif; /* red text bold for drawing attention*/\r\n\t        font-size: 10px;\r\n\t        font-weight: b
  old;\r\n\t        color:#F00; /*red text*/\r\n        }\r\n\r\n        .subhead1 {\r\n\t        font-family: Verdana, Arial, Helvetica, sans-serif;\r\n\t        font-size: 12px;\r\n\t        font-style: normal;\r\n\t        font-weight: bold;\r\n\t        color: #006633;\r\n\r\n        }\r\n        .auto-style12\r\n        {\r\n            font-family: Verdana, Arial, Helvetica,
  sans-serif;\r\n            color: #006600;\r\n        }\r\n        .auto-style14\r\n        {\r\n            font-family: Verdana, Geneva, Tahoma, sans-serif;\r\n            font-size: small;\r\n            color: #663300;\r\n        }\r\n        .auto-style4\r\n        {\r\n            color: #FF0000;\r\n        }\r\n        .auto-style3\r\n        {\r\n            font-family:
  Calibri, sans-serif;\r\n        }\r\n        .auto-style15\r\n        {\r\n            font-size: medium;\r\n        }\r\n        </style>\r\n\r\n<body style=\"margin: 0px\">\r\n    <form name=\"aspnetForm\" method=\"post\" action=\"./FishingRegs.aspx?ID=1\" id=\"aspnetForm\" class=\"mainform\">\r\n<input type=\"hidden\" name=\"__VIEWSTATE\" id=\"__VIEWSTATE\" value=\"/wEPDwUKMTQ
  1ODk1OTYyOA9kFgJmD2QWAgIFD2QWAgIBD2QWAgIBD2QWDAIBDw8WAh4EVGV4dGVkZAIHDzwrABECAA8WBh4HQ2FwdGlvbgUvPGZvbnQgY29sb3I9J2JsYWNrJyBzaXplPSczJz5BbGRlciBCcm9vazwvZm9udD4eC18hRGF0YUJvdW5kZx4LXyFJdGVtQ291bnQCAWQMFCsABBYIHgROYW1lBRNTZWN0aW9uIERlc2NyaXB0aW9uHgpJc1JlYWRPbmx5aB4EVHlwZRkrAh4JRGF0YUZpZWxkBRNTZWN0aW9uIERlc2NyaXB0aW9uFggfBAUEVG93bh8FaB8GGSsCHwcFBFRvd24WCB8EBQZDb3VudHkfBWgfBhkrAh8HB
  QZDb3VudHkWCB8EBRBBcXVhdGljIE51aXNhbmNlHwVoHwYZKwIfBwUQQXF1YXRpYyBOdWlzYW5jZRYCZg9kFgQCAQ9kFghmDw8WAh8ABSJCbGFjayBSaXZlciB0byBTYXJnZW50IFBvbmQgT3V0bGV0ZGQCAQ8PFgIfAAUJIENvdmVudHJ5ZGQCAg8PFgIfAAUIIE9ybGVhbnNkZAIDDw8WAh8ABQYmbmJzcDtkZAICDw8WAh4HVmlzaWJsZWhkZAIJDzwrABECAA8WBh8CZx8DAgIfAQWvATxmb250IGNvbG9yPSdyZWQnIHNpemU9JzInPlNwZWNpYWwgUmVndWxhdGlvbnMgU3VwZXJzZWRlIHRoZSBHZW5lcmFsIGF
  uZCBJY2UgRmlzaGluZyBSZWd1bGF0aW9ucyBCZWxvdyAtIFlvdSBtdXN0IGNvbXBseSB3aXRoIHRoZSBTcGVjaWFsIHJlZ3VsYXRpb25zIGZvciBlYWNoIHdhdGVyYm9keTwvZm9udD5kDBQrAAEWCB8EBRNTcGVjaWFsIFJlZ3VsYXRpb25zHwVoHwYZKwIfBwUTU3BlY2lhbCBSZWd1bGF0aW9ucxYCZg9kFgYCAQ9kFgJmDw8WAh8ABTpDbG9zZWQgdG8gRmlzaGluZzogU2Vjb25kIFNhdHVyZGF5IGluIEFwcmlsIHRocm91Z2ggTWF5IDMxZGQCAg9kFgJmDw8WAh8ABSlMYW5kbG9ja2VkIFNhbG1vbiBNaW5pb
  XVtIExlbmd0aCAxNyZxdW90O2RkAgMPDxYCHwhoZGQCCw88KwARAgAPFgYfAmcfAwIPHwEFNzxmb250IGNvbG9yPSdibGFjaycgc2l6ZT0nMyc+R2VuZXJhbCBSZWd1bGF0aW9uczwvZm9udD5kDBQrAAUWCB8EBQdTcGVjaWVzHwVoHwYZKwIfBwUHU3BlY2llcxYIHwQFBlNlYXNvbh8FaB8GGSsCHwcFBlNlYXNvbhYIHwQFBkxlbmd0aB8FaB8GGSsCHwcFBkxlbmd0aBYIHwQFC0RhaWx5IExpbWl0HwVoHwYZKwIfBwULRGFpbHkgTGltaXQWCB8EBQxMZWdhbCBNZXRob2QfBWgfBhkrAh8HBQxMZWdhbCBNZXR
  ob2QWAmYPZBYgAgEPZBYKZg8PFgIfAAUbQW5hZHJvbW91cyBBdGxhbnRpYyBTYWxtb24gZGQCAQ8PFgIfAAUOTm8gb3BlbiBzZWFzb25kZAICDw8WAh8ABQJOQWRkAgMPDxYCHwAFATBkZAIEDw8WAh8ABQJOQWRkAgIPZBYKZg8PFgIfAAUNTGFrZSBTdHVyZ2VvbmRkAgEPDxYCHwAFDk5vIG9wZW4gc2Vhc29uZGQCAg8PFgIfAAUCTkFkZAIDDw8WAh8ABQEwZGQCBA8PFgIfAAUCTkFkZAIDD2QWCmYPDxYCHwAFLkJyb29rIFRyb3V0IGFuZCBCcm93biBUcm91dCBhbmQgUmFpbmJvdyBUcm91dCBkZAIBDw8WA
  h8ABRwybmQgU2F0LiBpbiBBcHJpbCB0byBPY3QuIDMxZGQCAg8PFgIfAAUETm9uZWRkAgMPDxYCHwAFXlRvdGFsIG9mIGJyb29rICsgYnJvd24gKyByYWluYm93ID0gbm8gbW9yZSB0aGFuIDEyIFRvdGFsIG9mIGJyb3duICsgcmFpbmJvd3MgPSBubyBtb3JlIHRoYW4gNiBkZAIEDw8WAh8ABQdBbmdsaW5nZGQCBA9kFgpmDw8WAh8ABQpMYWtlIFRyb3V0ZGQCAQ8PFgIfAAUcMm5kIFNhdC4gaW4gQXByaWwgdG8gT2N0LiAzMWRkAgIPDxYCHwAFAjE4ZGQCAw8PFgIfAAU5VG90YWwgb2YgbGFrZSB0cm91dCA
  rIGxhbmRsb2NrZWQgc2FsbW9uID0gbm8gbW9yZSB0aGFuIDIgZGQCBA8PFgIfAAUHQW5nbGluZ2RkAgUPZBYKZg8PFgIfAAURTGFuZGxvY2tlZCBTYWxtb25kZAIBDw8WAh8ABRwybmQgU2F0LiBpbiBBcHJpbCB0byBPY3QuIDMxZGQCAg8PFgIfAAUCMTVkZAIDDw8WAh8ABTlUb3RhbCBvZiBsYWtlIHRyb3V0ICsgbGFuZGxvY2tlZCBzYWxtb24gPSBubyBtb3JlIHRoYW4gMiBkZAIEDw8WAh8ABQdBbmdsaW5nZGQCBg9kFgpmDw8WAh8ABQ1BbWVyaWNhbiBTaGFkZGQCAQ8PFgIfAAUcMm5kIFNhdC4gaW4gQ
  XByaWwgdG8gT2N0LiAzMWRkAgIPDxYCHwAFBiZuYnNwO2RkAgMPDxYCHwAFATBkZAIEDw8WAh8ABRtDYXRjaCAmYW1wOyBSZWxlYXNlIGFuZ2xpbmdkZAIHD2QWCmYPDxYCHwAFHkxhcmdlbW91dGggYW5kIFNtYWxsbW91dGggQmFzc2RkAgEPDxYCHwAFGjFzdCBTYXQuIGluIE1heSB0byBPY3QuIDMxZGQCAg8PFgIfAAUETm9uZWRkAgMPDxYCHwAFMVRvdGFsIG9mIGxhcmdlbW91dGggKyBzbWFsbG1vdXRoID0gbm8gbW9yZSB0aGFuIDVkZAIEDw8WAh8ABQdBbmdsaW5nZGQCCA9kFgpmDw8WAh8ABQdXYW$
  sZXllZGQCAQ8PFgIfAAUcMm5kIFNhdC4gaW4gQXByaWwgdG8gT2N0LiAzMWRkAgIPDxYCHwAFAjE1ZGQCAw8PFgIfAAUBM2RkAgQPDxYCHwAFB0FuZ2xpbmdkZAIJD2QWCmYPDxYCHwAFDU5vcnRoZXJuIFBpa2VkZAIBDw8WAh8ABRwybmQgU2F0LiBpbiBBcHJpbCB0byBPY3QuIDMxZGQCAg8PFgIfAAUCMjBkZAIDDw8WAh8ABQE1ZGQCBA8PFgIfAAUHQW5nbGluZ2RkAgoPZBYKZg8PFgIfAAULTXVza2VsbHVuZ2VkZAIBDw8WAh8ABRwybmQgU2F0LiBpbiBBcHJpbCB0byBPY3QuIDMxZGQCAg8PFgIfAAUCT
  kFkZAIDDw8WAh8ABQEwZGQCBA8PFgIfAAUHQW5nbGluZ2RkAgsPZBYKZg8PFgIfAAUNUmFpbmJvdyBTbWVsdGRkAgEPDxYCHwAFHDJuZCBTYXQuIGluIEFwcmlsIHRvIE9jdC4gMzFkZAICDw8WAh8ABQROb25lZGQCAw8PFgIfAAUETm9uZWRkAgQPDxYCHwAFB0FuZ2xpbmdkZAIMD2QWCmYPDxYCHwAFDFllbGxvdyBQZXJjaGRkAgEPDxYCHwAFHDJuZCBTYXQuIGluIEFwcmlsIHRvIE9jdC4gMzFkZAICDw8WAh8ABQROb25lZGQCAw8PFgIfAAUCNTBkZAIEDw8WAh8ABQdBbmdsaW5nZGQCDQ9kFgpmDw8WAh8
  ABQdDcmFwcGllZGQCAQ8PFgIfAAUcMm5kIFNhdC4gaW4gQXByaWwgdG8gT2N0LiAzMWRkAgIPDxYCHwAFAThkZAIDDw8WAh8ABQIyNWRkAgQPDxYCHwAFB0FuZ2xpbmdkZAIOD2QWCmYPDxYCHwAFEUFsbCBPdGhlciBTcGVjaWVzZGQCAQ8PFgIfAAUcMm5kIFNhdC4gaW4gQXByaWwgdG8gT2N0LiAzMWRkAgIPDxYCHwAFBE5vbmVkZAIDDw8WAh8ABQROb25lZGQCBA8PFgIfAAUHQW5nbGluZ2RkAg8PZBYKZg8PFgIfAAUGU2F1Z2VyZGQCAQ8PFgIfAAUOTm8gb3BlbiBzZWFzb25kZAICDw8WAh8ABQYmbmJzc
  DtkZAIDDw8WAh8ABQEwZGQCBA8PFgIfAAUCTkFkZAIQDw8WAh8IaGRkAg0PPCsAEQIADxYGHwJnHwNmHwEFOzxmb250IGNvbG9yPSdibGFjaycgc2l6ZT0nMyc+SWNlIEZpc2hpbmcgUmVndWxhdGlvbnM8L2ZvbnQ+ZAwUKwAFFggfBAUHU3BlY2llcx8FaB8GGSsCHwcFB1NwZWNpZXMWCB8EBQZTZWFzb24fBWgfBhkrAh8HBQZTZWFzb24WCB8EBQZMZW5ndGgfBWgfBhkrAh8HBQZMZW5ndGgWCB8EBQtEYWlseSBMaW1pdB8FaB8GGSsCHwcFC0RhaWx5IExpbWl0FggfBAUMTGVnYWwgTWV0aG9kHwVoHwYZKwI
  fBwUMTGVnYWwgTWV0aG9kZAITDw9kFgIeB29uQ2xpY2sFwAF3aW5kb3cub3BlbignaHR0cHM6Ly93d3cuc3VydmV5bW9ua2V5LmNvbS9yL29ubGluZWZpc2hpbmdyZWdzdG9vbCcsICdteXdpbmRvd2InLCd0b29sYmFyPXllcyxsb2NhdGlvbj15ZXMsZGlyZWN0b3JpZXM9eWVzLHN0YXR1cz15ZXMsIG1lbnViYXI9eWVzLHNjcm9sbGJhcnM9eWVzLGNvcHloaXN0b3J5PXllcyxyZXNpemFibGU9eWVzJylkGAUFHl9fQ29udHJvbHNSZXF1aXJlUG9zdEJhY2tLZXlfXxYBBSZjdGwwMCRDb250ZW50UGxhY2VIb
  2xkZXIxJGltZ2J0blN1cnZleQUjY3RsMDAkQ29udGVudFBsYWNlSG9sZGVyMSRndkljZVJlZ3MPPCsADAEIZmQFLmN0bDAwJENvbnRlbnRQbGFjZUhvbGRlcjEkZ3ZHZW5lcmFsUmVndWxhdGlvbnMPPCsADAEIAgFkBS5jdGwwMCRDb250ZW50UGxhY2VIb2xkZXIxJGd2U3BlY2lhbFJlZ3VsYXRpb25zDzwrAAwBCAIBZAUjY3RsMDAkQ29udGVudFBsYWNlSG9sZGVyMSRndkRldGFpbHMPPCsADAEIAgFkS26jok28fSsASK+QAZhqwZVto/0on+i6ATudwgOiIdQ=\" />\r\n\r\n\r\n<script src=\"/FWD
  /FW/ScriptResource.axd?d=qwbNTspuKlAYAAcALdZ-Bb5OQosvUzeWtwaxrBsumqu8kLE-kYdVvak8YpVGTSm7arF6edQPh-n5hY3M3coDFdOj4SKCCTTzc4JRz9WfcDzhiTrep7mTPPvPYZG0Ynr9H-EW-4C1GP4fsZkoMaQLWw2&amp;t=ffffffffaa73f696\" type=\"text/javascript\"></script>\r\n<script type=\"text/javascript\">\r\n//<![CDATA[\r\nif (typeof(Sys) === 'undefined') throw new Error('ASP.NET Ajax client-side framework faile
  d to load.');\r\n//]]>\r\n</script>\r\n\r\n<input type=\"hidden\" name=\"__VIEWSTATEGENERATOR\" id=\"__VIEWSTATEGENERATOR\" value=\"6DE5DA88\" />\r\n<input type=\"hidden\" name=\"__EVENTVALIDATION\" id=\"__EVENTVALIDATION\" value=\"/wEdAANYO8JTaOS6NWd+JaemJvMXdhR257qkzGvuhXj1Rr6InMhj3YNXhmt8k5oAyoHLfZaUQq9o7SQR3IusR83vn4K+Od2cVj1IzCGAiSX+1ZP48A==\" />\r\n        <header class=\"m
  ain\">\r\n            <div class=\"container\">\r\n                <div class=\"top cf\">\r\n                    <a href=\"http://vtfishandwildlife.com\">\r\n                        <img src=\"Images/vermont-fish-wildlife.png\" id=\"ctl00_logo\" alt=\"Vermont Fish &amp; Wildlife\" />\r\n                    </a>\r\n                </div>\r\n                <nav class=\"cf\">\r\n
                    <div class=\"menu\">\r\n                        <div>\r\n                            <ul>\r\n                                <li><a href=\"http://vtfishandwildlife.com/hunt\">Hunt</a></li>\r\n                                <li><a href=\"http://www.vtfishandwildlife.com/fish\">Fish</a></li>\r\n                                <li><a href=\"http://vtfishandwildlif
  e.com/licenses_and_lotteries\">Licenses & Lotteries</a></li>\r\n                                <li><a href=\"http://vtfishandwildlife.com/watch_wildlife\">Watch Wildlife</a></li>\r\n                                <li><a href=\"http://vtfishandwildlife.com/get_involved\">Get Involved</a></li>\r\n                                <li><a href=\"http://vtfishandwildlife.com/learn_mor
  e\">Learn More</a></li>\r\n                                <li><a href=\"http://vtfishandwildlife.com/about_us\">About Us</a></li>\r\n                            </ul>\r\n                        </div>\r\n                    </div>\r\n                </nav>\r\n            </div>\r\n        </header>\r\n        <header class=\"mobile\">\r\n            \r\n            <a class=\"re
  sponsive-menu-trigger\">Menu</a>\r\n            <a href=\"/\">\r\n                <img src=\"Images/mobile-logo.png\" alt=\"Vermont Fish & Wildlife\" id=\"mobile-logo\"></a>\r\n            \r\n        </header>\r\n        <div>\r\n            \r\n    <meta name=\"viewport\" content=\"width=device-width\" />\r\n    \r\n    <div class=\"container subpage-wrapper\">\r\n        <div
  class=\"topbar\">\r\n            <h1>Fishing Regulations</h1>\r\n        </div>\r\n        <div class=\"container subpage-container cf\">\r\n             <div class=\"main-content full-page fish\">\r\n                &nbsp;<div id=\"ctl00_ContentPlaceHolder1_Panel1\">\r\n\t\r\n                <table style=\"width: 100%\">\r\n                    <tr>\r\n                        <td
  >\r\n                            <span id=\"ctl00_ContentPlaceHolder1_lblMessage\" style=\"color: #FF0000; font-weight: 700; font-size: small;\"></span>\r\n                        </td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td>\r\n                            <a id=\"ctl00_ContentPlaceHolder1_HyperLink4\" class=\"auto-style15\" href=\
  "http://anrmaps.vermont.gov/websites/fishdigest/\">Back to Fishing Regulations Tool</a>\r\n                        </td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td>&nbsp;</td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td>\r\n                            <a id=\"ctl00_ContentPlaceHolder1_lbBackT
  oLookup\" class=\"auto-style15\" href=\"javascript:__doPostBack(&#39;ctl00$ContentPlaceHolder1$lbBackToLookup&#39;,&#39;&#39;)\">Back to Lookup Page</a>\r\n                        </td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td>&nbsp;</td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td>\r\n
                          <div>\r\n\t\t<table class=\"auto-style14\" cellspacing=\"0\" cellpadding=\"4\" rules=\"all\" border=\"1\" id=\"ctl00_ContentPlaceHolder1_gvDetails\" width=\"627\">\r\n\t\t\t<caption align=\"Left\">\r\n\t\t\t\t<font color='black' size='3'>Alder Brook</font>\r\n\t\t\t</caption><tr bgcolor=\"#1C5E55\">\r\n\t\t\t\t<th scope=\"col\"><font color=\"White\"><b>Sec
  tion Description</b></font></th><th scope=\"col\"><font color=\"White\"><b>Town</b></font></th><th scope=\"col\"><font color=\"White\"><b>County</b></font></th><th scope=\"col\"><font color=\"White\"><b>Aquatic Nuisance</b></font></th>\r\n\t\t\t</tr><tr bgcolor=\"#E3EAEB\">\r\n\t\t\t\t<td><font color=\"#333333\">Black River to Sargent Pond Outlet</font></td><td><font color=\"#333
  333\"> Coventry</font></td><td><font color=\"#333333\"> Orleans</font></td><td><font color=\"#333333\">&nbsp;</font></td>\r\n\t\t\t</tr>\r\n\t\t</table>\r\n\t</div>\r\n                        </td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td class=\"auto-style12\">\r\n                            <div>\r\n\t\t<table class=\"auto-style14\
  " cellspacing=\"0\" cellpadding=\"4\" rules=\"all\" border=\"1\" id=\"ctl00_ContentPlaceHolder1_gvSpecialRegulations\" width=\"627\">\r\n\t\t\t<caption align=\"Left\">\r\n\t\t\t\t<font color='red' size='2'>Special Regulations Supersede the General and Ice Fishing Regulations Below - You must comply with the Special regulations for each waterbody</font>\r\n\t\t\t</caption><tr bgco
  lor=\"#1C5E55\">\r\n\t\t\t\t<th scope=\"col\"><font color=\"White\"><b>Special Regulations</b></font></th>\r\n\t\t\t</tr><tr bgcolor=\"#E3EAEB\">\r\n\t\t\t\t<td><font color=\"#333333\">Closed to Fishing: Second Saturday in April through May 31</font></td>\r\n\t\t\t</tr><tr bgcolor=\"White\">\r\n\t\t\t\t<td><font color=\"#333333\">Landlocked Salmon Minimum Length 17&quot;</font></
  td>\r\n\t\t\t</tr>\r\n\t\t</table>\r\n\t</div>\r\n                        </td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td class=\"auto-style12\">\r\n                            <div>\r\n\t\t<table class=\"auto-style14\" cellspacing=\"0\" cellpadding=\"4\" rules=\"all\" border=\"1\" id=\"ctl00_ContentPlaceHolder1_gvGeneralRegulations\"
   width=\"627\">\r\n\t\t\t<caption align=\"Left\">\r\n\t\t\t\t<font color='black' size='3'>General Regulations</font>\r\n\t\t\t</caption><tr bgcolor=\"#1C5E55\">\r\n\t\t\t\t<th scope=\"col\"><font color=\"White\"><b>Species</b></font></th><th scope=\"col\"><font color=\"White\"><b>Season</b></font></th><th scope=\"col\"><font color=\"White\"><b>Length</b></font></th><th scope=\"co
  l\"><font color=\"White\"><b>Daily Limit</b></font></th><th scope=\"col\"><font color=\"White\"><b>Legal Method</b></font></th>\r\n\t\t\t</tr><tr bgcolor=\"#E3EAEB\">\r\n\t\t\t\t<td><font color=\"#333333\">Anadromous Atlantic Salmon </font></td><td><font color=\"#333333\">No open season</font></td><td><font color=\"#333333\">NA</font></td><td><font color=\"#333333\">0</font></td>
  <td><font color=\"#333333\">NA</font></td>\r\n\t\t\t</tr><tr bgcolor=\"White\">\r\n\t\t\t\t<td><font color=\"#333333\">Lake Sturgeon</font></td><td><font color=\"#333333\">No open season</font></td><td><font color=\"#333333\">NA</font></td><td><font color=\"#333333\">0</font></td><td><font color=\"#333333\">NA</font></td>\r\n\t\t\t</tr><tr bgcolor=\"#E3EAEB\">\r\n\t\t\t\t<td><fon
  t color=\"#333333\">Brook Trout and Brown Trout and Rainbow Trout </font></td><td><font color=\"#333333\">2nd Sat. in April to Oct. 31</font></td><td><font color=\"#333333\">None</font></td><td><font color=\"#333333\">Total of brook + brown + rainbow = no more than 12 Total of brown + rainbows = no more than 6 </font></td><td><font color=\"#333333\">Angling</font></td>\r\n\t\t\t<
  /tr><tr bgcolor=\"White\">\r\n\t\t\t\t<td><font color=\"#333333\">Lake Trout</font></td><td><font color=\"#333333\">2nd Sat. in April to Oct. 31</font></td><td><font color=\"#333333\">18</font></td><td><font color=\"#333333\">Total of lake trout + landlocked salmon = no more than 2 </font></td><td><font color=\"#333333\">Angling</font></td>\r\n\t\t\t</tr><tr bgcolor=\"#E3EAEB\">\
  r\n\t\t\t\t<td><font color=\"#333333\">Landlocked Salmon</font></td><td><font color=\"#333333\">2nd Sat. in April to Oct. 31</font></td><td><font color=\"#333333\">15</font></td><td><font color=\"#333333\">Total of lake trout + landlocked salmon = no more than 2 </font></td><td><font color=\"#333333\">Angling</font></td>\r\n\t\t\t</tr><tr bgcolor=\"White\">\r\n\t\t\t\t<td><font c
  olor=\"#333333\">American Shad</font></td><td><font color=\"#333333\">2nd Sat. in April to Oct. 31</font></td><td><font color=\"#333333\">&nbsp;</font></td><td><font color=\"#333333\">0</font></td><td><font color=\"#333333\">Catch &amp; Release angling</font></td>\r\n\t\t\t</tr><tr bgcolor=\"#E3EAEB\">\r\n\t\t\t\t<td><font color=\"#333333\">Largemouth and Smallmouth Bass</font></
  td><td><font color=\"#333333\">1st Sat. in May to Oct. 31</font></td><td><font color=\"#333333\">None</font></td><td><font color=\"#333333\">Total of largemouth + smallmouth = no more than 5</font></td><td><font color=\"#333333\">Angling</font></td>\r\n\t\t\t</tr><tr bgcolor=\"White\">\r\n\t\t\t\t<td><font color=\"#333333\">Walleye</font></td><td><font color=\"#333333\">2nd Sat.
  in April to Oct. 31</font></td><td><font color=\"#333333\">15</font></td><td><font color=\"#333333\">3</font></td><td><font color=\"#333333\">Angling</font></td>\r\n\t\t\t</tr><tr bgcolor=\"#E3EAEB\">\r\n\t\t\t\t<td><font color=\"#333333\">Northern Pike</font></td><td><font color=\"#333333\">2nd Sat. in April to Oct. 31</font></td><td><font color=\"#333333\">20</font></td><td><fo
  nt color=\"#333333\">5</font></td><td><font color=\"#333333\">Angling</font></td>\r\n\t\t\t</tr><tr bgcolor=\"White\">\r\n\t\t\t\t<td><font color=\"#333333\">Muskellunge</font></td><td><font color=\"#333333\">2nd Sat. in April to Oct. 31</font></td><td><font color=\"#333333\">NA</font></td><td><font color=\"#333333\">0</font></td><td><font color=\"#333333\">Angling</font></td>\r\
  n\t\t\t</tr><tr bgcolor=\"#E3EAEB\">\r\n\t\t\t\t<td><font color=\"#333333\">Rainbow Smelt</font></td><td><font color=\"#333333\">2nd Sat. in April to Oct. 31</font></td><td><font color=\"#333333\">None</font></td><td><font color=\"#333333\">None</font></td><td><font color=\"#333333\">Angling</font></td>\r\n\t\t\t</tr><tr bgcolor=\"White\">\r\n\t\t\t\t<td><font color=\"#333333\">Y
  ellow Perch</font></td><td><font color=\"#333333\">2nd Sat. in April to Oct. 31</font></td><td><font color=\"#333333\">None</font></td><td><font color=\"#333333\">50</font></td><td><font color=\"#333333\">Angling</font></td>\r\n\t\t\t</tr><tr bgcolor=\"#E3EAEB\">\r\n\t\t\t\t<td><font color=\"#333333\">Crappie</font></td><td><font color=\"#333333\">2nd Sat. in April to Oct. 31</fo
  nt></td><td><font color=\"#333333\">8</font></td><td><font color=\"#333333\">25</font></td><td><font color=\"#333333\">Angling</font></td>\r\n\t\t\t</tr><tr bgcolor=\"White\">\r\n\t\t\t\t<td><font color=\"#333333\">All Other Species</font></td><td><font color=\"#333333\">2nd Sat. in April to Oct. 31</font></td><td><font color=\"#333333\">None</font></td><td><font color=\"#333333\
  ">None</font></td><td><font color=\"#333333\">Angling</font></td>\r\n\t\t\t</tr><tr bgcolor=\"#E3EAEB\">\r\n\t\t\t\t<td><font color=\"#333333\">Sauger</font></td><td><font color=\"#333333\">No open season</font></td><td><font color=\"#333333\">&nbsp;</font></td><td><font color=\"#333333\">0</font></td><td><font color=\"#333333\">NA</font></td>\r\n\t\t\t</tr>\r\n\t\t</table>\r\n\t
  </div>\r\n                        </td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td class=\"auto-style12\">\r\n                            <div>\r\n\r\n\t</div>\r\n                        </td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td class=\"auto-style12\">\r\n                            <
  span class=\"auto-style4\"><strong>DISCLAIMER </strong></span></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td class=\"auto-style12\">\r\n                            <p class=\"MsoNormal\">\r\n                                <span>This application is a guidance document.&nbsp; The Vermont fishing regulations may be found at:&nbsp; </sp
  an>\r\n                            </p>\r\n                            <p class=\"MsoNormal\">\r\n                                <a id=\"ctl00_ContentPlaceHolder1_HyperLink3\" href=\"http://legislature.vermont.gov/statutes/section/10APPENDIX/002/00122\" target=\"_blank\">http://legislature.vermont.gov/statutes/section/10APPENDIX/002/00122</a>\r\n                                <
  span style=\"color:#1F497D\">&nbsp;</span></p>\r\n                        </td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td class=\"auto-style12\">\r\n                            <a id=\"ctl00_ContentPlaceHolder1_HyperLink2\" class=\"auto-style3\" href=\"http://www.vtfishandwildlife.com/about_us/contact_a_warden\" target=\"_blank\">Cont
  act a Warden</a>\r\n                        </td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td class=\"auto-style12\">&nbsp;</td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td class=\"auto-style12\">\r\n                                <input type=\"image\" name=\"ctl00$ContentPlaceHolder1$imgbtnS
  urvey\" id=\"ctl00_ContentPlaceHolder1_imgbtnSurvey\" src=\"Images/SurveyLink.png\" alt=\"Give us your feedback!\" onclick=\"window.open(&#39;https://www.surveymonkey.com/r/onlinefishingregstool&#39;, &#39;mywindowb&#39;,&#39;toolbar=yes,location=yes,directories=yes,status=yes, menubar=yes,scrollbars=yes,copyhistory=yes,resizable=yes&#39;);\" border=\"0\" />\r\n
        </td>\r\n                        <td class=\"auto-style12\">&nbsp;</td>\r\n                    </tr>\r\n\r\n                </table>\r\n                      \r\n           \r\n            \r\n</div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n        </div>\r\n\r\n        \r\n        <div class=\"container\">\r\n            <div id=\"newsletter\" class=\"c
  ontainer cf\">\r\n                <h2>E-mail News</h2>\r\n                <p>Be in the know about all Vermont Fish & Wildlife News by joining our E-mail mailing list.</p>\r\n                <div class=\"form\"><a href=\"http://visitor.r20.constantcontact.com/manage/optin?v=001AYBE7UAKClmYCXGJpCVt6FkdoZ7wgEf0L3IqL-dUB3XjA7zEBY93MPJeM2PcKLEKd-jT1qAlJs46d5t40_c79RcYlA3J62fQ\" target
  =\"_blank\" placeholder=\"enter your e-mail address\">Join our mailing list today</a></div>\r\n            </div>\r\n        </div>\r\n\r\n        <footer class=\"container\">\r\n            <div class=\"left\">\r\n                <p><a href=\"http://vtfishandwildlife.com/about_us/fish_wildlife_store\">Visit our store</a></p>\r\n            </div>\r\n            <div class=\"cent
  er\">\r\n                <p>Copyright © 2003-2016 Vermont Fish & Wildlife Department. All Rights Reserved.</p>\r\n                \r\n            </div>\r\n            <div class=\"right\">\r\n                <a href=\"https://www.facebook.com/vtfishandwildlife\"><img src=\"Images/social-facebook.png\" alt=\"Facebook\" /></a>\r\n                <a href=\"https://twitter.com/VTFis
  hWildlife\"><img src=\"Images/social-twitter.png\" alt=\"Twitter\" /></a>\r\n            </div>\r\n        </footer>\r\n        <script src=\"../Scripts/tabs.js\"></script>\r\n        <script src=\"../Scripts/scripts.js\"></script>\r\n        <script src=\"../Scripts/bootstrap.min.js\"></script>\r\n        <!--[if lte IE 8]>\r\n        <script src=\"http://html5shiv.googlecode.co
  m/svn/trunk/html5.js\"></script>\r\n        <![endif]-->\r\n    </form>\r\n</body>\r\n</html>\r\n
  """

  test "the truth" do
    assert 1 + 1 == 2
  end
end
