defmodule WaterbodyTest do
  use ExUnit.Case
  doctest FishDataGatherer.Waterbody

  @expected_response [
    %{daily_limit: "0", fish: %{name: "Anadromous Atlantic Salmon"}, legal_method: "NA", length: "NA", season: "No open season",
    waterbody: %{access: "", acres: "55", aquatic_nuisance: "", county: "Essex", motors_allowed: "No", name: "Mud Pond", other_restrictions: "5mph", special_regulations: [], town: "Granby"}},
    %{daily_limit: "0", fish: %{name: "Lake Sturgeon"}, legal_method: "NA", length: "NA", season: "No open season",
    waterbody: %{access: "", acres: "55", aquatic_nuisance: "", county: "Essex", motors_allowed: "No", name: "Mud Pond", other_restrictions: "5mph", special_regulations: [], town: "Granby"}},
    %{daily_limit: "Total of brook + brown + rainbow = no more than 6", fish: %{name: "Brook Trout and Brown Trout and Rainbow Trout"}, legal_method: "Angling", length: "None", season: "2nd Sat. in April to Oct. 31",
    waterbody: %{access: "", acres: "55", aquatic_nuisance: "", county: "Essex", motors_allowed: "No", name: "Mud Pond", other_restrictions: "5mph", special_regulations: [], town: "Granby"}},
    %{daily_limit: "Total of lake trout + landlocked salmon = no more than 2", fish: %{name: "Lake Trout"}, legal_method: "Angling", length: "18\"", season: "2nd Sat. in April to Oct. 31",
    waterbody: %{access: "", acres: "55", aquatic_nuisance: "", county: "Essex", motors_allowed: "No", name: "Mud Pond", other_restrictions: "5mph", special_regulations: [], town: "Granby"}},
    %{daily_limit: "Total of lake trout + landlocked salmon = no more than 2", fish: %{name: "Landlocked Salmon"}, legal_method: "Angling", length: "15\"", season: "2nd Sat. in April to Oct. 31",
    waterbody: %{access: "", acres: "55", aquatic_nuisance: "", county: "Essex", motors_allowed: "No", name: "Mud Pond", other_restrictions: "5mph", special_regulations: [], town: "Granby"}},
    %{daily_limit: "<\nfont color=\"#333333\">0", fish: %{name: "American Shad"}, legal_method: "Catch & Release angling", length: "", season: "2nd Sat. in April to Oct. 31",
    waterbody: %{access: "", acres: "55", aquatic_nuisance: "", county: "Essex", motors_allowed: "No", name: "Mud Pond", other_restrictions: "5mph", special_regulations: [], town: "Granby"}},
    %{daily_limit: "0", fish: %{name: "Largemouth and Smallmouth Bass"}, legal_method: "Catch & release angling w/ artificial lures and flies on\nly", length: "None", season: "Dec. 1st to Fri. before 2nd Sat. in June",
    waterbody: %{access: "", acres: "55", aquatic_nuisance: "", county: "Essex", motors_allowed: "No", name: "Mud Pond", other_restrictions: "5mph", special_regulations: [], town: "Granby"}},
    %{daily_limit: "Total of largemouth + smallmouth = no more than 5", fish: %{name: "Largemouth and Smallmouth Bass"}, legal_method: "Angling", length: "10\"", season: "2nd Sat. in June To Nov. 30",
    waterbody: %{access: "", acres: "55", aquatic_nuisance: "", county: "Essex", motors_allowed: "No", name: "Mud Pond", other_restrictions: "5mph", special_regulations: [], town: "Granby"}},
    %{daily_limit: "3", fish: %{name: "Walleye"}, legal_method: "Angling, Ice Fishing", length: "18\"", season: "1st Sat. in May to March 15",
    waterbody: %{access: "", acres: "55", aquatic_nuisance: "", county: "Essex", motors_allowed: "No", name: "Mud Pond", other_restrictions: "5mph", special_regulations: [], town: "Granby"}},
    %{daily_limit: "5", fish: %{name: "Northern Pike"}, legal_method: "Angling, Ice Fishing", length: "20\"", season: "All year",
    waterbody: %{access: "", acres: "55", aquatic_nuisance: "", county: "Essex", motors_allowed: "No", name: "Mud Pond", other_restrictions: "5mph", special_regulations: [], town: "Granby"}},
    %{daily_limit: "0", fish: %{name: "Muskellunge"}, legal_method: "Catch & release angling w/ artificial lures and flies only", length: "NA", season: "All year",
    waterbody: %{access: "", acres: "55", aquatic_nuisance: "", county: "Essex", motors_allowed: "No", name: "Mud Pond", other_restrictions: "5mph", special_regulations: [], town: "Granby"}},
    %{daily_limit: "None", fish: %{name: "Rainbow Smelt"}, legal_method: "Angling, Ice Fishing", length: "None", season: "All year",
    waterbody: %{access: "", acres: "55", aquatic_nuisance: "", county: "Essex", motors_allowed: "No", name: "Mud Pond", other_restrictions: "5mph", special_regulations: [], town: "Granby"}},
    %{daily_limit: "50", fish: %{name: "Yellow Perch"}, legal_method: "Angling, Ic\ne Fishing", length: "None", season: "All year",
    waterbody: %{access: "", acres: "55", aquatic_nuisance: "", county: "Essex", motors_allowed: "No", name: "Mud Pond", other_restrictions: "5mph", special_regulations: [], town: "Granby"}},
    %{daily_limit: "25", fish: %{name: "Crappie"}, legal_method: "Angling, Ice Fishing", length: "8\"", season: "All year",
    waterbody: %{access: "", acres: "55", aquatic_nuisance: "", county: "Essex", motors_allowed: "No", name: "Mud Pond", other_restrictions: "5mph", special_regulations: [], town: "Granby"}},
    %{daily_limit: "None", fish: %{name: "All Other Species"}, legal_method: "Angling, Ice Fishing", length: "None", season: "All year",
    waterbody: %{access: "", acres: "55", aquatic_nuisance: "", county: "Essex", motors_allowed: "No", name: "Mud Pond", other_restrictions: "5mph", special_regulations: [], town: "Granby"}},
    %{daily_limit: "None", fish: %{name: "Carp, Suckers, Bowfin, Mullet (Redhorse), Gar"}, legal_method: "Angling, Bow w/ arrow attached to line\n, Ice fishing", length: "None", season: "All Year",
    waterbody: %{access: "", acres: "55", aquatic_nuisance: "", county: "Essex", motors_allowed: "No", name: "Mud Pond", other_restrictions: "5mph", special_regulations: [], town: "Granby"}},
    %{daily_limit: "0", fish: %{name: "Sauger"}, legal_method: "NA", length: "", season: "No open season",
    waterbody: %{access: "", acres: "55", aquatic_nuisance: "", county: "Essex", motors_allowed: "No", name: "Mud Pond", other_restrictions: "5mph", special_regulations: [], town: "Granby"}},
    %{daily_limit: "0", fish: %{name: "Anadromous Atlantic Salmon"}, legal_method: "NA", length: "NA", season: "No open season",
    waterbody: %{access: "", acres: "55", aquatic_nuisance: "", county: "Essex", motors_allowed: "No", name: "Mud Pond", other_restrictions: "5mph", special_regulations: [], town: "Granby"}},
    %{daily_limit: "0", fish: %{name: "Lake Sturgeon"}, legal_method: "NA", length: "NA", season: "No open season",
    waterbody: %{access: "", acres: "55", aquatic_nuisance: "", county: "Essex", motors_allowed: "No", name: "Mud Pond", other_restrictions: "5mph", special_regulations: [], town: "Granby"}},
    %{daily_limit: "0", fish: %{name: "Brook Trout and Brown Trout and Rainbow Trout"}, legal_method: "Ice Fishing", length: "NA", season: "Closed",
    waterbody: %{access: "", acres: "55", aquatic_nuisance: "", county: "Essex", motors_allowed: "No", name: "Mud Pond", other_restrictions: "5mph", special_regulations: [], town: "Granby"}},
    %{daily_limit: "0", fish: %{name: "Lake Trout"}, legal_method: "Ice Fishing", length: "NA", season: "Closed",
    waterbody: %{access: "", acres: "55", aquatic_nuisance: "", county: "Essex", motors_allowed: "No", name: "Mud Pond", other_restrictions: "5mph", special_regulations: [], town: "Granby"}},
    %{daily_limit: "0", fish: %{name: "Landlocked Salmon"}, legal_method: "Ice Fishing", length: "NA", season: "Closed",
    waterbody: %{access: "", acres: "55", aquatic_nuisance: "", county: "Essex", motors_allowed: "No", name: "Mud Pond", other_restrictions: "5mph", special_regulations: [], town: "Granby"}},
    %{daily_limit: "0", fish: %{name: "American Shad"}, legal_method: "Ice Fishing", length: "NA", season: "Closed",
    waterbody: %{access: "", acres: "55", aquatic_nuisance: "", county: "Essex", motors_allowed: "No", name: "Mud Pond", other_restrictions: "5mph", special_regulations: [], town: "Granby"}},
    %{daily_limit: "0", fish: %{name: "Largemouth and Smallmouth Bass"}, legal_method: "Ice Fishing", length: "NA", season: "Closed",
    waterbody: %{access: "", acres: "55", aquatic_nuisance: "", county: "Essex", motors_allowed: "No", name: "Mud Pond", other_restrictions: "5mph", special_regulations: [], town: "Granby"}},
    %{daily_limit: "3", fish: %{name: "Walleye"}, legal_method: "Ice Fishing", length: "18\"", season: "1st Sat. in May to March 15",
    waterbody: %{access: "", acres: "55", aquatic_nuisance: "", county: "Essex", motors_allowed: "No", name: "Mud Pond", other_restrictions: "5mph", special_regulations: [], town: "Granby"}},
    %{daily_limit: "5", fish: %{name: "Northern Pike"}, legal_method: "Ice Fishing", length: "20\"", season: "All year",
    waterbody: %{access: "", acres: "55", aquatic_nuisance: "", county: "Essex", motors_allowed: "No", name: "Mud Pond", other_restrictions: "5mph", special_regulations: [], town: "Granby"}},
    %{daily_limit: "0", fish: %{name: "Muskellunge"}, legal_method: "Ice Fishing", length: "NA", season: "Closed",
    waterbody: %{access: "", acres: "55", aquatic_nuisance: "", county: "Essex", motors_allowed: "No", name: "Mud Pond", other_restrictions: "5mph", special_regulations: [], town: "Granby"}},
    %{daily_limit: "None", fish: %{name: "Rainbow Smelt"}, legal_method: "Ice Fishing", length: "None", season: "All year",
    waterbody: %{access: "", acres: "55", aquatic_nuisance: "", county: "Essex", motors_allowed: "No", name: "Mud Pond", other_restrictions: "5mph", special_regulations: [], town: "Granby"}},
    %{daily_limit: "50", fish: %{name: "Yellow Perch"}, legal_method: "Ice Fishing", length: "None", season: "All year",
    waterbody: %{access: "", acres: "55", aquatic_nuisance: "", county: "Essex", motors_allowed: "No", name: "Mud Pond", other_restrictions: "5mph", special_regulations: [], town: "Granby"}},
    %{daily_limit: "25", fish: %{name: "Crappie<\n/font>"}, legal_method: "Ice Fishing", length: "8\"", season: "All year",
    waterbody: %{access: "", acres: "55", aquatic_nuisance: "", county: "Essex", motors_allowed: "No", name: "Mud Pond", other_restrictions: "5mph", special_regulations: [], town: "Granby"}},
    %{daily_limit: "None", fish: %{name: "All Other Species"}, legal_method: "Ice Fish\ning", length: "None", season: "All year",
    waterbody: %{access: "", acres: "55", aquatic_nuisance: "", county: "Essex", motors_allowed: "No", name: "Mud Pond", other_restrictions: "5mph", special_regulations: [], town: "Granby"}},
    %{daily_limit: "None", fish: %{name: "Carp, Suckers, Bowfin, Mullet (Redhorse), Gar"}, legal_method: "Ice fishing", length: "None", season: "All Year",
    waterbody: %{access: "", acres: "55", aquatic_nuisance: "", county: "Essex", motors_allowed: "No", name: "Mud Pond", other_restrictions: "5mph", special_regulations: [], town: "Granby"}},
    %{daily_limit: "0", fish: %{name: "Sauger"}, legal_method: "NA", length: "", season: "No open season",
    waterbody: %{access: "", acres: "55", aquatic_nuisance: "", county: "Essex", motors_allowed: "No", name: "Mud Pond", other_restrictions: "5mph", special_regulations: [], town: "Granby"}}
  ]

  test "parse/1 correctly parses an html body" do
    {:ok, body} = File.read("test/data/waterbody_html.txt")
    assert FishDataGatherer.Waterbody.parse(Macro.unescape_string(body)) == @expected_response
  end
end
